//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urunTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int id { get; set; }
        public string kullanici { get; set; }
        public string sifre { get; set; }
    }
}
